version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.3.0
  golangci-lint: valimail/golangci-lint@volatile

executors:
  go-system:
    docker:
      - image: circleci/golang:latest

jobs:
  test-job:
    resource_class: small
    executor: go-system
    steps:
      - checkout
      - run:
          name: Set up test files
          command: |
            mkdir server
            mv test/go.mod server/go.mod
            mv test/go.sum server/go.sum
            mv test/main.go server/main.go
            mv test/golangci.yml server/.golangci.yml
            cd server
            go mod download
            go mod vendor
      - golangci-lint/lint:
          checkout: false
          working-directory: server

workflows:
  build:
    jobs:
      - orb-tools/lint
      - test-job
      