version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.3.0
  golangci-lint: valimail/golangci-lint@volatile

executors:
  go-system:
    docker:
      - image: circleci/golang:latest

workflows:
  build:
    jobs:
       - orb-tools/pack:
          name: pack
       - orb-tools/test-in-builds:
          attach-workspace: true
          orb-name: golangci-lint
          test-steps:
            - orb-tools/local-test-build:
                test-config-location: test/test.yml
          name: test
          # context: orb-publishing
          requires:
            - pack
